[package]
name = "gatcha-machine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.11"
eframe = "0.22.0"
egui = "0.22.0"
font-kit = "0.11.0"
rand = "0.8.5"
